[EMP-21164] fix: Seeking not working for streams with ads
EricssonBroadcastServices/iOSClientExposurePlayback pull request #129
Opened 2024-04-15 13:59 UTC by robert-pelka

Refactored ServerSideAdService in order to fix a bug with seeking not possible for streams with server side ads.

2024-04-15 14:43 UTC, jkochaniec requested changes

2024-04-15 14:43 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +            guard let `self` = self else {
`guard let self else {` - should be enough here

2024-04-15 14:43 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +        for (index, content) in self.allTimelineContent.enumerated() {
calling `self` seems to be unneeded here

2024-04-15 14:43 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +            if !self.alreadyPlayedAds.contains(content) {
no need to use `self` here

2024-04-15 14:43 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +    private func handleNotWatchedYetAd(_ content: TimelineContent, _ start: Int64, _ end: Int64, _ timeInMil: Int64) {
I would rename `timeInMil` to something more descriptive `timeInMilliseconds`

2024-04-15 14:43 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +        guard let point,
unneeded `self` usage inside function

2024-04-15 14:43 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +        // Send EMP analytics
unneeded self usage inside function

2024-04-16 10:42 UTC, jkochaniec requested changes

2024-04-16 10:42 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
>          // Some content may not have the `timeInMil` 0 when start. It seems like `PeriodicTimeObserverToPlayer` may have a slight delay and then timeInMil may be higher than the `start`. [ Add a seco
`timeInMil` - > `timeInMiliseconds` in comment

2024-04-16 10:42 UTC, jkochaniec commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +        guard timeInMiliseconds.rounded() + 10 == start.rounded() + 10 ||
Can we name 10 somehow?

2024-04-16 11:36 UTC, robert-pelka commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +        guard let point,
removed

2024-04-16 11:36 UTC, robert-pelka commented on Sources/iOSClientExposurePlayback/Services/AdService/ServerSideAdService.swift
> +        // Send EMP analytics
removed

2024-04-16 13:55 UTC, jkochaniec approved these changes

2024-04-17 06:08 UTC, merged